### ISSUE TITLE
Add tox

### ISSUE THREAD

**Issue by efe** [Hipo/hipo-drf-exceptions#21]
Basically, `tox` is a tool for running the same code in different Python environments.

We'll add tests. However, tests run only the _developers_' Python version. If we have a tox, It will run on the all Python versions which we support on the `pyproject.toml`.

Reference:
https://tox.readthedocs.io/en/latest/#basic-example

We may achieve this after https://github.com/Hipo/hipo-drf-exceptions/pull/20/.

**Comment by gokselcoban** [comment]
@onuralken Can you check this if you have time next week?

**Comment by efe** [comment]
Thanks @onuralken!
