### ISSUE TITLE
FEATURE: Change DjangoValidationError keys to DRF's NON_FIELD_ERRORS_KEY

### ISSUE THREAD

**Issue by omerfarukabaci** [Hipo/hipo-drf-exceptions#23]
If one raises `Django`'s `ValidationError`, `hipo-drf-exceptions` returns `__all__` as the error key, however in general we are using `non_field_errors` (default `NON_FIELD_ERRORS_KEY` of `DRF`, see [here](https://www.django-rest-framework.org/api-guide/settings/#non_field_errors_key)). What about changing this `__all__` key to the current `NON_FIELD_ERRORS_KEY` setting of the `DRF` on the `hipo-drf-exceptions` level?

**Comment by yigitguler** [comment]
Sounds good, but this will be a breaking change for all existing APIs. They should update this carefully.

**Comment by omerfarukabaci** [comment]
We may add a settings for this, something like `DJANGO_NON_FIELD_ERRORS_KEY`. It's default would be "__all__", and then consumers can change it to "non_field_errors" if they wish. What do you think?

**Comment by yigitguler** [comment]
I believe the default value should be the new one (DJANGO_NON_FIELD_ERRORS_KEY). Old projects can override this to __all__ What do you think @efe

**Comment by omerfarukabaci** [comment]
I am closing this since it is implemented. https://github.com/Hipo/hipo-drf-exceptions/pull/24
